### ISSUE TITLE
What are the requirements for the motherboard in this project？

### ISSUE THREAD

**Issue by 98Distance** [pfn/EnragedRabbitOnRRF#1]
hello，I happened to find this project，and the readme.md has declared the firmware of 3.34 . But I'd like to know more about this projet to determin if I can use it in my voron2.4.  
THE QUESTION I WANT TO KNOW MOST IS： is this project replaced the ERCF-easy-brd, and the dirver should be privite by duet board.
If it is this ,  I think i'd better get a extention board.

My english may not very well
Looking forward to your relpay

**Comment by pfn** [comment]
Duetwifi + duex5

Or any duet3 plus expansion boards as necessary to have enough drivers

The easybrd is not supported. However expansions such as https://github.com/gixxerfast/Canned-ERCF-board would be a possibility on duet3

**Comment by 98Distance** [comment]
THANK YOU VERY MUCH!
